apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task03-rb-admin
  namespace: dev
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task03-rb-view
  namespace: dev
subjects:
- kind: User
  name: ken
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-view
  apiGroup: rbac.authorization.k8s.io