apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task02-crb
subjects:
- kind: Group
  name: system:serviceaccount:prometheus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: task02-role
  apiGroup: rbac.authorization.k8s.io